#!/bin/bash
set -ex -o pipefail

update-initramfs -kall -u
INITRDS=(/boot/initrd.img-*)

unmkinitramfs "${INITRDS[0]}" initramfs/
find initramfs/

test -e initramfs/early/kernel/x86/microcode/GenuineIntel.bin
echo '# everything seems ok'

